---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: doom-deployment
  namespace: kubedoom
   
    
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
  selector:
    matchLabels:
      app: doom
  template:
    metadata:
      labels:
        app: doom    
    spec:
      hostNetwork: true
      serviceAccountName: kubedoom
      containers:
      - name: doom
        image: storaxdev/kubedoom:0.5.0
        ports:
        - containerPort: 5900          
          protocol: TCP       
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kubedoom
  namespace: kubedoom
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kubedoom
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
  - kind: ServiceAccount
    name: kubedoom
    namespace: kubedoom
