---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redmine
  namespace: redmine
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redmine
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: redmine
    spec:
      containers:
      - image: redmine:4.1.1
        name: redmine
        env:
          - name: REDMINE_DB_POSTGRES
            value: "pgs-service"
          - name: REDMINE_DB_USERNAME
            value: "pgs_user"
          - name: REDMINE_DB_DATABASE
            value: "testDB"
          - name: REDMINE_DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: pw-redmine
                key: PASS
          - name: REDMINE_SECRET_KEY_BASE
            valueFrom:
              secretKeyRef:
                name: pw-redmine
                key: KEY
        ports:
        - containerPort: 3000
          protocol: TCP
